// <auto-generated />
using System;
using EZmatchApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EZmatchApi.Migrations
{
    [DbContext(typeof(EZmatchDbContext))]
    [Migration("20261003191832_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EZmatchApi.Models.Block", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uuid")
                        .HasColumnName("court_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.HasKey("Id")
                        .HasName("pk_blocks");

                    b.HasIndex("CourtId", "StartsAt")
                        .HasDatabaseName("ix_blocks_court_id_starts_at");

                    b.ToTable("blocks", null, t =>
                        {
                            t.HasCheckConstraint("ck_blocks_range", "ends_at > starts_at");
                        });
                });

            modelBuilder.Entity("EZmatchApi.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid")
                        .HasColumnName("club_id");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uuid")
                        .HasColumnName("court_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("payment_status");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<DateTime?>("ReminderSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reminder_sent_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("CourtId")
                        .HasDatabaseName("ix_bookings_court_id");

                    b.HasIndex("ClubId", "StartsAt")
                        .HasDatabaseName("ix_bookings_club_id_starts_at");

                    b.HasIndex("CustomerId", "StartsAt")
                        .HasDatabaseName("ix_bookings_customer_id_starts_at");

                    b.ToTable("bookings", null, t =>
                        {
                            t.HasCheckConstraint("ck_bookings_range", "ends_at > starts_at");
                        });
                });

            modelBuilder.Entity("EZmatchApi.Models.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<int>("BookingHorizonDays")
                        .HasColumnType("integer")
                        .HasColumnName("booking_horizon_days");

                    b.Property<string>("BotInstructions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("bot_instructions");

                    b.Property<int>("CancellationMinHours")
                        .HasColumnType("integer")
                        .HasColumnName("cancellation_min_hours");

                    b.Property<int?>("ChatwootAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("chatwoot_account_id");

                    b.Property<int?>("ChatwootInboxId")
                        .HasColumnType("integer")
                        .HasColumnName("chatwoot_inbox_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("MaxActiveBookingsPerCustomer")
                        .HasColumnType("integer")
                        .HasColumnName("max_active_bookings_per_customer");

                    b.Property<int>("MinLeadMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("min_lead_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("slug");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("time_zone");

                    b.HasKey("Id")
                        .HasName("pk_clubs");

                    b.HasIndex("ChatwootInboxId")
                        .IsUnique()
                        .HasDatabaseName("ix_clubs_chatwoot_inbox_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_clubs_slug");

                    b.ToTable("clubs", (string)null);
                });

            modelBuilder.Entity("EZmatchApi.Models.Court", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid")
                        .HasColumnName("club_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCovered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_covered");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sport");

                    b.HasKey("Id")
                        .HasName("pk_courts");

                    b.HasIndex("ClubId")
                        .HasDatabaseName("ix_courts_club_id");

                    b.ToTable("courts", (string)null);
                });

            modelBuilder.Entity("EZmatchApi.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid")
                        .HasColumnName("club_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_blocked");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("ClubId", "Phone")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_club_id_phone");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("EZmatchApi.Models.SlotTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uuid")
                        .HasColumnName("court_id");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("pk_slot_templates");

                    b.HasIndex("CourtId", "DayOfWeek", "StartTime")
                        .IsUnique()
                        .HasDatabaseName("ix_slot_templates_court_id_day_of_week_start_time");

                    b.ToTable("slot_templates", null, t =>
                        {
                            t.HasCheckConstraint("ck_slot_templates_duration", "duration_minutes > 0");
                        });
                });

            modelBuilder.Entity("EZmatchApi.Models.Block", b =>
                {
                    b.HasOne("EZmatchApi.Models.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blocks_courts_court_id");

                    b.Navigation("Court");
                });

            modelBuilder.Entity("EZmatchApi.Models.Booking", b =>
                {
                    b.HasOne("EZmatchApi.Models.Club", null)
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_clubs_club_id");

                    b.HasOne("EZmatchApi.Models.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_courts_court_id");

                    b.HasOne("EZmatchApi.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_customers_customer_id");

                    b.Navigation("Court");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EZmatchApi.Models.Court", b =>
                {
                    b.HasOne("EZmatchApi.Models.Club", "Club")
                        .WithMany("Courts")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_courts_clubs_club_id");

                    b.Navigation("Club");
                });

            modelBuilder.Entity("EZmatchApi.Models.Customer", b =>
                {
                    b.HasOne("EZmatchApi.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customers_clubs_club_id");

                    b.Navigation("Club");
                });

            modelBuilder.Entity("EZmatchApi.Models.SlotTemplate", b =>
                {
                    b.HasOne("EZmatchApi.Models.Court", "Court")
                        .WithMany("SlotTemplates")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_slot_templates_courts_court_id");

                    b.Navigation("Court");
                });

            modelBuilder.Entity("EZmatchApi.Models.Club", b =>
                {
                    b.Navigation("Courts");
                });

            modelBuilder.Entity("EZmatchApi.Models.Court", b =>
                {
                    b.Navigation("SlotTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
